# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev
- main
- feature/*

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  submodules: true

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

# npm audit is broken: https://github.com/facebook/create-react-app/issues/11174
# specifying a custom build path, and moving the config file there
- script: |
    cd client
    npm install --no-audit
    npm audit --omit=dev
    BUILD_PATH='../app_dist' npm run build
    cp ../staticwebapp.config.json ../app_dist/staticwebapp.config.json
  displayName: 'npm install and build'
  env: # set environment variables that are used during build time here
    REACT_APP_MSAL_CLIENT_ID: b4e280de-2c62-4226-a09b-616acbe03b31
    REACT_APP_MSAL_AUTHORITY: https://login.microsoftonline.com/common
    REACT_APP_SIGN_IN_REDIRECT: https://icy-desert-098cf4a0f-dev.eastus2.1.azurestaticapps.net/
    REACT_APP_SIGN_OUT_REDIRECT: https://icy-desert-098cf4a0f-dev.eastus2.1.azurestaticapps.net/
    REACT_APP_FB_API_KEY: AIzaSyCdAB0DHnQo0gEgeWlRE-hS5HR0SSpvZnM
    REACT_APP_FB_AUTH_DOMAIN: cfg-volunteer-portal-dev.firebaseapp.com
    REACT_APP_FB_PROJECT_ID: cfg-volunteer-portal-dev
    REACT_APP_FB_STORAGE_BUCKET: cfg-volunteer-portal-dev.appspot.com
    REACT_APP_FB_MESSAGING_SENDER_ID: '999099573017'
    REACT_APP_FB_APP_ID: 1:999099573017:web:8900acb08d870522d8db88

- task: AzureStaticWebApp@0
  inputs:
    production_branch: 'main' # defines which branch is the main site, other branches get previews
    app_location: 'app_dist' # App built files cwd
    api_location: 'server' # Api source code path relative to cwd
    skip_api_build: false # Build the app backend to Functions 
    skip_app_build: true # handled by react in script step
    output_location: '' # empty because we're skipping the app build
    cwd: '$(System.DefaultWorkingDirectory)' # Working directory - optional
    azure_static_web_apps_api_token: $(swa_deploy_token)