# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev
- main
- feature/functions-and-db

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  submodules: true

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd client
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  inputs:
    production_branch: 'main' # defines which branch is the main site, other branches get previews
    app_location: 'client' # App built files cwd
    api_location: 'server' # Api source code path relative to cwd
    skip_api_build: false # Build the app backend to Functions 
    skip_app_build: true # handled by react in script step
    output_location: 'build' # empty because we're skipping the app build
    cwd: '$(System.DefaultWorkingDirectory)' # Working directory - optional
    azure_static_web_apps_api_token: $(swa_deploy_token)